# Generated by Django 4.0 on 2021-12-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialdistancelevel',
            name='criterion',
            field=models.TextField(max_length=1000),
        ),
    ]
